services:
  postgres:
    image: postgres:16
    container_name: postgres-meetung
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "51332:5432"
    networks:
      - meetung_backend
  meetung:
    image: ghcr.io/zenthaidev/meetung:latest-dev
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-meetung:5432/MeeTung?schema=public&sslmode=disable&pgbouncer=false"
      AUTH_SECRET: "secret"
      AUTH_DISCORD_ID: "secret"
      AUTH_DISCORD_SECRET: "secret"
    ports:
      - "3001:3000"
    networks:
      - meetung_backend
volumes:
  postgres_data:

networks:
  meetung_backend:
    driver: bridge
