name: meetung

on:
  push:
    branches: ["main", "dev"]
    tags:
      - "*"

env:
  IMAGE_NAME: ghcr.io/zenthaidev/meetung
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  AUTH_DISCORD_ID: ${{ secrets.AUTH_DISCORD_ID }}
  AUTH_DISCORD_SECRET: ${{ secrets.AUTH_DISCORD_SECRET }}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_IO_USERNAME }}
          password: ${{ secrets.GHCR_IO_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v3
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          AUTH_SECRET: ${{ env.AUTH_SECRET }}
          AUTH_DISCORD_ID: ${{ env.AUTH_DISCORD_ID }}
          AUTH_DISCORD_SECRET: ${{ env.AUTH_DISCORD_SECRET }}
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_type == 'tag' && !contains(github.ref_name, '-') }}
            type=raw,value=latest-dev,enable=${{ github.ref_type == 'branch' }}
            type=raw,value=${{ github.ref_name }}
            type=raw,value=${{ github.sha }},enable=${{ github.ref_type == 'branch' }}
          flavor: |
            latest=false

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./apps/nextjs/Dockerfile
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
